name: 'Labels Update'
description: 'Updates repository labels.'
inputs:
  token:
    description: 'GitHub token used by action.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'Owner and repository name. For example, "Codertocat/Hello-World".'
    default: ${{ github.repository }}
    required: true
  config:
    description: 'Path to file or config as value with generate settings. (Possible representation types: "Json" or "Yaml".)'
    default: .github/config.yml
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'box'  
  color: 'gray-dark'
