
name: Labels

on: workflow_dispatch

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}
    - name: Sync
      uses: micnncim/action-label-syncer@v1
      with:
        token: ${{ github.token }}
